# Assignment

Import numpy as np


In [1]:
import numpy as np

Make a python list => [1,2,3,4,5]

Convert it into numpy array and print it

In [2]:
list = [1,2,3,4]
arr = np.array(list)
arr

array([1, 2, 3, 4])

Make a python matrix (3 x 3) => [[1,2,3],[4,5,6],[7,8,9]]

Convert it into numpy array and print it

In [3]:
mat = [[1,2,3],[4,5,6],[7,8,9]]
arr1 = np.array(mat)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Make a matrix (3 x 3) using built-in methods (like arange(), reshape() etc.):

[ [1,3,5],

[7,9,11],

[13,15,17] ]

In [4]:
matrix = np.arange(1,18,2).reshape(3,3)
matrix

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

Create a numpy array with 10 random numbers from 0 to 10 (there should be few numbers greater than 1)

In [5]:

arr2 = np.random.randint(10,size=10)
arr2


array([4, 3, 8, 9, 1, 9, 3, 3, 9, 1])

Create numpy array => [1,2,3,4,5] and convert it to 2D array with 5 rows

In [6]:
arr3=np.arange(1,6)
arr3.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

Print the shape of the above created array

In [7]:
arr3.shape

(5,)

Create a numpy array with 10 elements in it. Access and print its 3rd, 4th and 9th element.

In [8]:
arr4 = np.arange(10)
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr4[2]   #3rd element

2

In [10]:
arr4[3]   #4th element

3

In [11]:
arr4[8]   #9th element

8

Print alternate elements of that array

In [12]:
arr4[0::2]

array([0, 2, 4, 6, 8])

Change last 3 elements into 100 using broadcasting and print

In [13]:
arr4[-3:] = 100
arr4

array([  0,   1,   2,   3,   4,   5,   6, 100, 100, 100])

Create a 5 x 5 matrix (fill it with any element you like), print it.

Then print the middle (3 x 3) matrix.

In [14]:
mat5 = np.arange(25).reshape(5,5)
mat5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [15]:
mat5[1:4,1:4]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])